### ISSUE TITLE
Have you tested this?

### ISSUE THREAD

**Issue by fawazahmed0** [maggie-j-liu/mail#1]
Please refer [this](https://www.appmaildev.com/en/dkim) to test dkim is setup properly or not.
For me it's not working( i.e not showing DKIM pass)

**Comment by maggie-j-liu** [comment]
Yep, I have tested this and it works! 
<img width="90" alt="image" src="https://user-images.githubusercontent.com/63619830/174696599-fb355885-ac95-40df-afc8-180e76c2e27e.png">

Not sure why it's not working for you; does anyone else have the same problem?

**Comment by fawazahmed0** [comment]
ok, thanks, Maybe I am doing something wrong here,  I will try again.

**Comment by fawazahmed0** [comment]
Thanks, everything is working now, I copied your [code](https://github.com/maggie-j-liu/mail/blob/main/src/index.ts)
